
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04@sha256:ea73825f3d88a23c355ac2f9fdc6bd960fec90171c12c572109b36a558f77bb8

    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "This-Is-A-Secure-Password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
        - mssql_data:/var/opt/mssql
    restart: always
volumes:
  mssql_data: 
